#!/bin/bash
BASEDIR=$(dirname $0)

echo --application--
$BASEDIR/phpunit.phar --colors $BASEDIR/tests/application.php

echo --Hooks--
$BASEDIR/phpunit.phar --colors $BASEDIR/tests/hooks.php

echo --Config--
$BASEDIR/phpunit.phar --colors $BASEDIR/tests/config.php

echo --Router--
$BASEDIR/phpunit.phar --colors $BASEDIR/tests/router.php
